name: Testes Postman - Usuários

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Newman e Reporter HTML
        run: |
          npm install -g newman newman-reporter-htmlextra

      - name: Executar coleção Usuários
        run: |
          newman run ./usuarios.json \
          -g ./globals.json \
          -e ./environment.json \
          --delay-request 1 \
          --reporters cli,htmlextra \
          --reporter-htmlextra-export ./results/report-usuarios.html

      - name: Fazer upload do relatório
        uses: actions/upload-artifact@v4
        with:
          name: report-usuarios
          path: ./results/report-usuarios.html
